package com.iemr.hwc.service.quickConsultation;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.doReturn;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.verify;

import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import com.google.gson.JsonArray;
import com.google.gson.JsonObject;
import com.iemr.hwc.data.nurse.BeneficiaryVisitDetail;
import com.iemr.hwc.data.quickConsultation.BenClinicalObservations;
import com.iemr.hwc.data.quickConsultation.ExternalLabTestOrder;
import com.iemr.hwc.data.quickConsultation.PrescriptionDetail;
import com.iemr.hwc.repo.nurse.BenVisitDetailRepo;
import com.iemr.hwc.repo.quickConsultation.BenChiefComplaintRepo;
import com.iemr.hwc.repo.quickConsultation.BenClinicalObservationsRepo;
import com.iemr.hwc.repo.quickConsultation.ExternalTestOrderRepo;
import com.iemr.hwc.repo.quickConsultation.PrescriptionDetailRepo;
import com.iemr.hwc.service.benFlowStatus.CommonBenStatusFlowServiceImpl;
import com.iemr.hwc.service.common.transaction.CommonDoctorServiceImpl;
import com.iemr.hwc.service.common.transaction.CommonNurseServiceImpl;
import com.iemr.hwc.service.generalOPD.GeneralOPDDoctorServiceImpl;
import com.iemr.hwc.testutil.NurseVisitRequest;
import com.iemr.hwc.testutil.PopulatedMocks;

/**
 * A quick consultation is the shortest visit path: the nurse records the visit and the
 * doctor records complaints, observations, a prescription and any external tests, with no
 * history or examination forms in between.
 */
@DisplayName("QuickConsultationServiceImpl")
class QuickConsultationServiceImplTest {

	private QuickConsultationServiceImpl service;
	private CommonNurseServiceImpl commonNurseServiceImpl;
	private CommonDoctorServiceImpl commonDoctorServiceImpl;
	private GeneralOPDDoctorServiceImpl generalOPDDoctorServiceImpl;
	private CommonBenStatusFlowServiceImpl commonBenStatusFlowServiceImpl;
	private PrescriptionDetailRepo prescriptionDetailRepo;
	private BenClinicalObservationsRepo benClinicalObservationsRepo;
	private ExternalTestOrderRepo externalTestOrderRepo;

	@BeforeEach
	void setUp() throws Exception {
		service = new QuickConsultationServiceImpl();
		commonNurseServiceImpl = PopulatedMocks.inject(service, "commonNurseServiceImpl",
				CommonNurseServiceImpl.class);
		commonDoctorServiceImpl = PopulatedMocks.inject(service, "commonDoctorServiceImpl",
				CommonDoctorServiceImpl.class);
		generalOPDDoctorServiceImpl = PopulatedMocks.inject(service, "generalOPDDoctorServiceImpl",
				GeneralOPDDoctorServiceImpl.class);
		commonBenStatusFlowServiceImpl = PopulatedMocks.inject(service, "commonBenStatusFlowServiceImpl",
				CommonBenStatusFlowServiceImpl.class);
		prescriptionDetailRepo = PopulatedMocks.inject(service, "prescriptionDetailRepo",
				PrescriptionDetailRepo.class);
		benClinicalObservationsRepo = PopulatedMocks.inject(service, "benClinicalObservationsRepo",
				BenClinicalObservationsRepo.class);
		externalTestOrderRepo = PopulatedMocks.inject(service, "externalTestOrderRepo",
				ExternalTestOrderRepo.class);
		PopulatedMocks.injectCollaborators(service);

		// The saved records come back with the ids the database generated, which is what the
		// service reads to decide whether the save worked.
		doAnswer(invocation -> {
			BenClinicalObservations saved = invocation.getArgument(0);
			saved.setClinicalObservationID(31L);
			return saved;
		}).when(benClinicalObservationsRepo).save(any());
		doAnswer(invocation -> {
			ExternalLabTestOrder saved = invocation.getArgument(0);
			// The id is generated by the database and has no setter, so it is placed the way
			// the persistence layer would.
			org.springframework.test.util.ReflectionTestUtils.setField(saved, "externalTestOrderID", 41L);
			return saved;
		}).when(externalTestOrderRepo).save(any());

		doReturn(0).when(commonNurseServiceImpl).getMaxCurrentdate(any(), any(), any());
		// A quick consultation records the visit against the session it was captured in.
		doReturn(10L).when(commonNurseServiceImpl).saveBeneficiaryVisitDetails(any(BeneficiaryVisitDetail.class),
				any());
		doReturn(20L).when(commonNurseServiceImpl).generateVisitCode(anyLong(), any(), any());
		doReturn("{\"counsellingProvided\":\"a||b\"}").when(generalOPDDoctorServiceImpl)
				.getGeneralOPDDiagnosisDetails(anyLong(), anyLong());
	}

	private static JsonObject nurseRequest() {
		// The vitals of a quick consultation are read from "vitalsDetails", not the
		// "vitalDetails" the longer visit forms use.
		JsonArray chiefComplaints = new JsonArray();
		chiefComplaints.add(new JsonObject());
		return NurseVisitRequest.forCategory("NCD screening").with("vitalsDetails", new JsonObject())
				.with("chiefComplaintList", chiefComplaints).build();
	}

	private static JsonObject caseSheet() {
		JsonObject caseSheet = new JsonObject();
		caseSheet.addProperty("beneficiaryRegID", 1L);
		caseSheet.addProperty("benVisitID", 10L);
		caseSheet.addProperty("visitCode", 20L);
		caseSheet.addProperty("createdBy", "doctor1");
		caseSheet.add("chiefComplaints", new JsonArray());
		caseSheet.add("clinicalObservations", new JsonObject());
		caseSheet.add("prescription", new JsonArray());
		caseSheet.addProperty("externalInvestigation", "Ultrasound at the district hospital");
		return caseSheet;
	}

	@Nested
	@DisplayName("saving a nurse visit")
	class SavingANurseVisit {

		@Test
		@DisplayName("saves the visit and answers with the visit code")
		void savesTheVisit() throws Exception {
			String response = service.quickConsultNurseDataInsert(nurseRequest(), "Bearer token");

			assertThat(response).contains("\"visitCode\":\"20\"").contains("Data saved successfully");
			verify(commonNurseServiceImpl).saveBeneficiaryVisitDetails(any(BeneficiaryVisitDetail.class), any());
		}

		@Test
		@DisplayName("reports the visit as already captured when one is recorded for the same reason")
		void reportsAnAlreadyCapturedVisit() throws Exception {
			doReturn(1).when(commonNurseServiceImpl).getMaxCurrentdate(any(), any(), any());

			assertThat(service.quickConsultNurseDataInsert(nurseRequest(), "Bearer token"))
					.contains("Data already saved");
		}

		@Test
		@DisplayName("rejects a request that carries no visit details")
		void rejectsARequestWithoutVisitDetails() {
			assertThatThrownBy(() -> service.quickConsultNurseDataInsert(new JsonObject(), "Bearer token"))
					.isInstanceOf(Exception.class).hasMessage("Invalid input");
		}

		@Test
		@DisplayName("moves the beneficiary on to the doctor once the visit is saved")
		void movesTheBeneficiaryOn() throws Exception {
			service.quickConsultNurseDataInsert(nurseRequest(), "Bearer token");

			verify(commonBenStatusFlowServiceImpl).updateBenFlowNurseAfterNurseActivity(any(), any(), any(), any(),
					any(), any(), any(), any(), any(), any(), any(), any(), any(), any(), any());
		}
	}

	@Nested
	@DisplayName("recording the consultation")
	class RecordingTheConsultation {

		@Test
		@DisplayName("records the complaints, observations, prescription and external tests")
		void recordsTheConsultation() throws Exception {
			assertThat(service.quickConsultDoctorDataInsert(caseSheet(), "Bearer token")).isNotNull();
		}

		@Test
		@DisplayName("records the complaints of a case sheet")
		void recordsTheComplaints() {
			assertThat(service.saveBeneficiaryChiefComplaint(caseSheet())).isNotNull();
		}

		@Test
		@DisplayName("records the observations of a case sheet")
		void recordsTheObservations() throws Exception {
			assertThat(service.saveBeneficiaryClinicalObservations(caseSheet())).isNotNull();
		}

		@Test
		@DisplayName("records the external tests ordered on a case sheet")
		void recordsTheExternalTests() {
			assertThat(service.saveBeneficiaryExternalLabTestOrderDetails(caseSheet())).isNotNull();
		}

		@Test
		@DisplayName("records the prescription and reports the id it was given")
		void recordsThePrescription() {
			PrescriptionDetail prescription = new PrescriptionDetail();
			prescription.setPrescriptionID(7L);
			doReturn(prescription).when(prescriptionDetailRepo).save(any());

			assertThat(service.saveBenPrescriptionForANC(new PrescriptionDetail())).isEqualTo(7L);
		}

		@Test
		@DisplayName("updates the observations of a recorded consultation")
		void updatesTheObservations() throws Exception {
			assertThat(service.updateBeneficiaryClinicalObservations(caseSheet())).isNotNull();
		}

		@Test
		@DisplayName("updates a consultation that was already recorded")
		void updatesTheConsultation() throws Exception {
			assertThat(service.updateGeneralOPDQCDoctorData(caseSheet(), "Bearer token")).isNotNull();
		}
	}

	@Nested
	@DisplayName("reading a consultation back")
	class ReadingAConsultationBack {

		@Test
		@DisplayName("gathers the visit screen of a consultation with the complaints recorded on it")
		void gathersTheVisitScreen() {
			// The complaints reach this screen as a JSON document that is parsed back into an
			// array, so the collaborator has to answer with one.
			doReturn("[{\"chiefComplaint\":\"Fever\"}]").when(commonNurseServiceImpl)
					.getBenChiefComplaints(anyLong(), anyLong());

			assertThat(service.getBenDataFrmNurseToDocVisitDetailsScreen(1L, 20L)).contains("Fever");
		}

		@Test
		@DisplayName("gathers the vitals screen of a consultation")
		void gathersTheVitalsScreen() {
			assertThat(service.getBeneficiaryVitalDetails(1L, 20L)).isNotNull();
		}

		@Test
		@DisplayName("gathers the decision-support screen of a consultation")
		void gathersTheDecisionSupportScreen() {
			assertThat(service.getBeneficiaryCdssDetails(1L, 10L)).isNotNull();
		}

		@Test
		@DisplayName("gathers the doctor sections of a visit into one document")
		void gathersTheDoctorSections() {
			assertThat(service.getBenCaseRecordFromDoctorQuickConsult(1L, 20L)).isNotNull().contains("findings");
		}
	}

	@Nested
	@DisplayName("rolling a failed save back")
	class RollingAFailedSaveBack {

		@Test
		@DisplayName("deletes the records a failed nurse save had already written")
		void deletesTheRecordsOfAFailedSave() throws Exception {
			BenVisitDetailRepo benVisitDetailRepo = PopulatedMocks.inject(service, "benVisitDetailRepo",
					BenVisitDetailRepo.class);
			BenChiefComplaintRepo benChiefComplaintRepo = PopulatedMocks.inject(service, "benChiefComplaintRepo",
					BenChiefComplaintRepo.class);
			doReturn(20L).when(benVisitDetailRepo).getVisitCode(any(), any());

			service.deleteVisitDetails(nurseRequest());

			verify(benChiefComplaintRepo).deleteVisitDetails(20L);
			verify(benVisitDetailRepo).deleteVisitDetails(20L);
		}

		@Test
		@DisplayName("does nothing for a request that never created a visit")
		void doesNothingWithoutVisitDetails() throws Exception {
			BenVisitDetailRepo benVisitDetailRepo = PopulatedMocks.inject(service, "benVisitDetailRepo",
					BenVisitDetailRepo.class);

			service.deleteVisitDetails(new JsonObject());

			verify(benVisitDetailRepo, never()).getVisitCode(any(), any());
		}
	}
}
